# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c2eddae3a3b3a562ea7d5ae0f2164d56feb55c0b3fbb38120a957d47954f39dad1adf98b0bae90ac7cba75cc1e85001c2c850115ee256f895596f3ba345a1e4

test:
  secret_key_base: 46b7e6d45b473da0441da4d44fa5173fcf64df2f3db175ed869080f8244003f0d65554295e8e98231600e636f5b5e0ebcae765d0d15813d5286fbaf3f625425b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
